### ISSUE TITLE
`panic: interface conversion: interface {} is nil, not string` group by collation

### ISSUE THREAD

**Issue by coffeegoddd** [dolthub/go-mysql-server#1503]
Running tests against a Dolt sql-server results in the following panic. This did not panic in Dolt v0.51.13, but panics as of `v0.51.14.`

```
panic: interface conversion: interface {} is nil, not string

goroutine 4141 [running]:
github.com/dolthub/go-mysql-server/sql/plan.groupingKey(0x14001bf97a0?, {0x140007ac680, 0xd, 0x20?}, {0x140011136c0, 0xe, 0xe})
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/group_by.go:438 +0x280
github.com/dolthub/go-mysql-server/sql/plan.(*groupByGroupingIter).compute(0x140006aa300, 0x10f4d0448?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/group_by.go:347 +0x80
github.com/dolthub/go-mysql-server/sql/plan.(*groupByGroupingIter).Next(0x140006aa300, 0x14001dec5a0)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/group_by.go:320 +0x88
github.com/dolthub/go-mysql-server/sql/plan.(*projectIter).Next(0x14001c9df80, 0x1056bcd2c?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/project.go:151 +0x34
github.com/dolthub/go-mysql-server/sql/plan.(*topRowsIter).computeTopRows(0x140021ffc80, 0x14001dec5a0)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/sort.go:434 +0xd0
github.com/dolthub/go-mysql-server/sql/plan.(*topRowsIter).Next(0x140021ffc80, 0x14002192340?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/sort.go:399 +0x2c
github.com/dolthub/go-mysql-server/sql/plan.(*limitIter).Next(0x14001c9dfb0, 0x1056bcd2c?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/limit.go:178 +0x78
github.com/dolthub/go-mysql-server/sql/plan.transactionCommittingIter.Next(...)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/transaction_committing_iter.go:112
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0x140012296d0, 0x105585b98?)
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/sql/plan/process.go:381 +0x30
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func2()
	/Users/dustin/go/pkg/mod/github.com/dolthub/go-mysql-server@v0.14.1-0.20221222180637-32cbe451b56e/server/handler.go:406 +0x1fc
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/dustin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/dustin/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa4
```

The last query logged by the server before that panic is:
```sql
SELECT repositories.*, COUNT(repository_stars.repository_id_fk) AS star_count FROM (SELECT * FROM repositories WHERE (NOT is_deleted) AND (user_id_fk = 'user-id-1') UNION SELECT repositories.* FROM repositories JOIN `repository_collaborators` ON repositories.id = repository_collaborators.repository_id_fk WHERE (NOT repositories.is_deleted) AND (repository_collaborators.user_id_fk = 'user-id-1') AND (repository_collaborators.is_invitation = false) UNION SELECT repositories.* FROM repositories JOIN `organization_members` ON repositories.organization_id_fk = organization_members.organization_id_fk WHERE (NOT repositories.is_deleted) AND (organization_members.user_id_fk = 'user-id-1') UNION SELECT * FROM repositories WHERE (NOT is_deleted) AND (visibility = 1)) AS `repositories` LEFT JOIN `repository_stars` ON repositories.id = repository_stars.repository_id_fk GROUP BY repositories.id, repositories.name, repositories.description, repositories.user_id_fk, repositories.organization_id_fk, repositories.visibility, repositories.size, repositories.updated_at, repositories.created_at, repositories.last_write_timestamp, repositories.is_deleted, repositories.fork_root_repo_id_fk, repositories.fork_parent_repo_id_fk ORDER BY star_count DESC, repositories.id ASC LIMIT 21;
```

**Comment by fulghum** [comment]
Dustin tracked this down to [this line in `group_by.go`](https://github.com/dolthub/go-mysql-server/pull/1476/files#diff-15ff619fecf8baa7fb922a3be3a2bb093cf5839017cb6586a6d7e6c386b6ef26R438). From the error message, it seems like the expression evaluated to nil, so `v` was not able to be cast to a string and caused the panic.

**Comment by fulghum** [comment]
Here's a simple repro case: 
```sql
create table t (pk int primary key, c1 varchar(10));
insert into t values (1, 'foo'), (2, 'foo'), (3, NULL);
select c1, count(c1) from t group by c1;
```

**Comment by fulghum** [comment]
Got the fix merged into go-mysql-server; I'll keep an eye on the GMS bump for Dolt and make sure it gets into Dolt today for ya.
