### ISSUE TITLE
Panic when using memory implemenation

### ISSUE THREAD

**Issue by matthew1838** [dolthub/go-mysql-server#603]
Hi guys, does memory implementation not fully compatible?

I got panic when the primary was duplicated.

Below is code to reproduce.

```go
package it

import (
	stdsql "database/sql"
	"fmt"
	sqle "github.com/dolthub/go-mysql-server"
	"github.com/dolthub/go-mysql-server/auth"
	"github.com/dolthub/go-mysql-server/memory"
	"github.com/dolthub/go-mysql-server/server"
	"github.com/dolthub/go-mysql-server/sql"
	"github.com/dolthub/go-mysql-server/sql/information_schema"
	_ "github.com/go-sql-driver/mysql"
	"testing"
	"time"
)

func createTestDatabase() *memory.Database {
	const (
		dbName    = "mydb"
		tableName = "mytable"
	)

	db := memory.NewDatabase(dbName)
	table := memory.NewTable(tableName, sql.Schema{
		{Name: "name", Type: sql.Text, Nullable: false, Source: tableName},
		{Name: "email", Type: sql.Text, Nullable: false, Source: tableName, PrimaryKey: true},
	})

	db.AddTable(tableName, table)
	ctx := sql.NewEmptyContext()
	table.Insert(ctx, sql.NewRow("John Doe", "john@doe.com"))
	table.Insert(ctx, sql.NewRow("John Doe", "johnalt@doe.com"))
	table.Insert(ctx, sql.NewRow("Jane Doe", "jane@doe.com"))
	table.Insert(ctx, sql.NewRow("Evil Bob", "evilbob@gmail.com"))
	return db
}

func TestMyFunc(t *testing.T) {
	engine := sqle.NewDefault(
		sql.NewDatabaseProvider(
			createTestDatabase(),
			information_schema.NewInformationSchemaDatabase(),
		))
	config := server.Config{
		Protocol: "tcp",
		Address:  "localhost:33306",
		Auth:     auth.NewNativeSingle("root", "123456", auth.AllPermissions),
	}

	s, err := server.NewDefaultServer(config, engine)

	if err != nil {
		panic(err)
	}

	go func() {
		err := s.Start()
		if err != nil {
			panic(err)
		}
	}()
	// Wait for server to start
	time.Sleep(50 * time.Millisecond)

	dsn := fmt.Sprintf("%s:%s@tcp(%s)/%s?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true",
		"root",
		"123456",
		config.Address,
		"mydb",
	)
	stddb, err := stdsql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}

	// Will cause panic
	_, err = stddb.Exec("INSERT INTO mytable(`name`, `email`) values ('my_name', 'evilbob@gmail.com') ON DUPLICATE KEY UPDATE `name` = '1'")
	if err != nil {
		panic(err)
	}
}

```

Panic message
```
panic: runtime error: index out of range [1] with length 1

goroutine 38 [running]:
github.com/dolthub/go-mysql-server/memory.(*tableEditor).checkUniquenessConstraints(0xc000424e70, {0xc000562460, 0xc0005645a0, 0x2})
	../github.com/dolthub/go-mysql-server/memory/table.go:646 +0x330
github.com/dolthub/go-mysql-server/memory.(*tableEditor).Insert(0xc000424e70, 0x17c4fa0, {0xc000562460, 0xc00059ad30, 0xc000562460})
	../github.com/dolthub/go-mysql-server/memory/table.go:466 +0x77
github.com/dolthub/go-mysql-server/sql/plan.(*insertIter).Next(0xc0003fe820)
	../github.com/dolthub/go-mysql-server/sql/plan/insert.go:308 +0x41d
github.com/dolthub/go-mysql-server/sql/plan.(*tableEditorIter).Next(0xc000530500)
	../github.com/dolthub/go-mysql-server/sql/plan/table_editor.go:52 +0x62
github.com/dolthub/go-mysql-server/sql/plan.(*accumulatorIter).Next(0xc000424f30)
	../github.com/dolthub/go-mysql-server/sql/plan/row_update_accumulator.go:217 +0xb5
github.com/dolthub/go-mysql-server/sql/plan.(*trackedRowIter).Next(0xc000530540)
	../github.com/dolthub/go-mysql-server/sql/plan/process.go:291 +0x2e
github.com/dolthub/go-mysql-server.transactionCommittingIter.Next(...)
	../github.com/dolthub/go-mysql-server/engine.go:259
github.com/dolthub/go-mysql-server/server.(*Handler).doQuery.func3()
	../github.com/dolthub/go-mysql-server/server/handler.go:349 +0x9a
created by github.com/dolthub/go-mysql-server/server.(*Handler).doQuery
	../github.com/dolthub/go-mysql-server/server/handler.go:343 +0x965
```

**Comment by zachmu** [comment]
You found a bug. Vinai will get on top of this.

**Comment by VinaiRachakonda** [comment]
Pr is in review. Should be in soon
